### ISSUE TITLE
WifiUDP.h cannot be found

### ISSUE THREAD

**Issue by McOrvas** [envy/esp-knx-ip#24]
Hi envy,

Thanks for this very cool library! I have a short question about the included "WifiUDP.h" in "esp-knx-ip.h". On my system this header file is written "WiFiUdp.h", and so I have to change the notation of this to compile my project. Do you use a system which is not case sensitive or do I just have another version installed? I'm using "esp8266" in version 2.4.0.

Thanks and regards,
McOrvas

**Comment by envy** [comment]
Hi,

Yeah, I use Windows... I copied this from some example and never bothered to check as it worked...

I fixed it, thank you.

**Comment by McOrvas** [comment]
Sorry to write again about this issue, but the correct notation is "WiFiUdp.h" with an upper case "F".
