### ISSUE TITLE
Question on Physical Address. Manual Entry

### ISSUE THREAD

**Issue by ascillato** [envy/esp-knx-ip#34]
Hi,

Setting the Physical Address by code was intended to be like the following? Or there is another way?

```
  // Set Physical KNX Address of ESP KNX (Optional)
  address_t physaddr;
  physaddr.pa.area=1;
  physaddr.pa.line=1;
  physaddr.pa.member=1;
  knx.physical_address_set(physaddr);
```

**Comment by envy** [comment]
Yes, either that way or like this:
```c++
knx.physical_address_set(GA_to_address(1, 2, 3));
```

**Comment by envy** [comment]
Oops, yeah sorry. I confused group and physical addresses for a moment there...

I will add a PA_to_address method for this.
