### ISSUE TITLE
ESPAsyncUDP stop working on Arduino Core STAGE

### ISSUE THREAD

**Issue by ascillato** [envy/esp-knx-ip#62]
@envy

Hi Nico,

I'm testing KNX using the last Arduino STAGE Core and now the library ESPAsyncUDP no longer works there. I opened an issue to me-no-dev (https://github.com/me-no-dev/ESPAsyncUDP/issues/32).

The other library WIFIUDP works fine with last Arduino Core.

**Comment by envy** [comment]
Hi,

I tested sending and receiving on 2.5.0-beta2 with the async library and it worked fine for me, no reset.
I used lwIP v2 Lower Memory.

The async library seems abandoned. My plan was at some point to integrate the lwIP commands directly into esp-knx-ip but currently I don't have the time to read lwIP documentation as I don't just want to copy paste from the library.
