### ISSUE TITLE
ESP ETS5 registration

### ISSUE THREAD

**Issue by angy71** [envy/esp-knx-ip#69]
Hi,
How we can register esp-knx-ip to ETS5, or is there are other option how to put it in to the scenario with the rest of KNX Items?

**Comment by envy** [comment]
You can't. This is not a "real" KNX device and therefore has no product catalog (.knxprod) file available.

However you can add a dummy device (e.g., GIRA has dummy devices in their product catalog) to your ETS project and assign it the same group addresses you assigned in the web interface. This is a nice way for ETS to know when telegrams need to pass from one medium to another (e.g., from TP to IP or vice-versa) and therefore ETS is able to configure filter tables for the IP router.

Buth other than that, there is no way with this library
