### ISSUE TITLE
Receive messages on group 2/1/0

### ISSUE THREAD

**Issue by brunohorta82** [envy/esp-knx-ip#73]
Hello, thanks for the great library :)
I register my switches like this way:
` for (auto &item : items)
  {
    callback_id_t switchesCallbackId = knx.callback_register(String(item.name), switchesCallback, &item);
    knx.callback_assign(switchesCallbackId, knx.GA_to_address(2, 1, i));
    i++;`

the final result for 2 switches is like 2/1/1 and 2/1/2, I have any method to handle with the telegrams sent to 2/1/0 ?
if I receive on message on this group address I want to turn on/turn off all switches.

**Comment by brunohorta82** [comment]
I made this way, is correct?
  callback_id_t switchesCallbackId = knx.callback_register("ALL", allwitchesCallback);
  knx.callback_assign(switchesCallbackId, knx.GA_to_address(2, 1, 0));

**Comment by envy** [comment]
Hi,

Sure, you can do it this way.
